---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    allow:
      - dependency-name: "husky"
      - dependency-name: "jest"
      - dependency-name: "ts-*"
      - dependency-name: "tsup"
      - dependency-name: "typescript"
    open-pull-requests-limit: 5
    versioning-strategy: increase-if-necessary
